// Generated by CoffeeScript 1.10.0
(function() {
  var User, express, mongoose, router;

  express = require('express');

  router = express.Router();

  mongoose = require('mongoose');

  User = mongoose.model('users');

  router.get('/', function(req, res) {
    var u1;
    u1 = new User({
      name: 'klausgao'
    });
    return u1.findByname(function(err, docs) {
      if (err) {
        console.log(err);
        return;
      }
      return res.send({
        title: 'cnnode',
        data: docs
      });
    });
  });

  module.exports = router;

}).call(this);
