// Generated by CoffeeScript 1.10.0
(function() {
  var express, router, spider;

  express = require('express');

  router = express.Router();

  spider = require('../spiders/cnspiders');

  router.get('/', function(req, res) {
    var sp;
    sp = new spider('https://cnodejs.org/');
    return sp.getData(res);
  });

  module.exports = router;

}).call(this);
