// Generated by CoffeeScript 1.10.0
(function() {
  var BaseUrl, async, cheerio, express, qs, router, spider, superagent, url;

  express = require('express');

  router = express.Router();

  spider = require('../spiders/cnspiders');

  superagent = require('superagent');

  cheerio = require('cheerio');

  url = require('url');

  qs = require('querystring');

  async = require('async');

  BaseUrl = "https://cnodejs.org/";

  router.get('/', function(req, res) {
    var totalPage;
    totalPage = 10;
    return superagent.get('https://cnodejs.org/').end(function(err, response) {
      var $, allPages, item, page;
      if (err) {
        return console.error(err);
      } else {
        $ = cheerio.load(response.text);
        page = $('div.pagination ul li:last-child a').attr('href').trim();
        allPages = (function() {
          var i, ref, results;
          results = [];
          for (item = i = 1, ref = totalPage; 1 <= ref ? i < ref : i > ref; item = 1 <= ref ? ++i : --i) {
            results.push(url.resolve(BaseUrl, '?tab=all&page=' + item));
          }
          return results;
        })();
        return async.mapLimit(allPages, 2, function(page, callback) {
          console.log('spider :' + page);
          return setTimeout(function() {
            console.log('begin:' + page);
            return superagent.get(page).end(function(err, content) {
              var users;
              if (err) {
                return callback(err);
              } else {
                $ = cheerio.load(content.text);
                users = [];
                return $('#topic_list div.cell').each(function(idx, data) {
                  var $user;
                  $user = $(this).find('a').first();
                  return users.push({
                    name: $user.find('img').attr('title').trim(),
                    img: $user.find('img').attr('src').trim(),
                    href: 'https://cnodejs.org' + $user.attr('href').trim()
                  });
                });
              }
            });
          }, 100);
        }, function(err, result) {
          console.log(err);
          return console.log(result);
        });
      }
    });
  });

  module.exports = router;

}).call(this);
