// Generated by CoffeeScript 1.10.0
(function() {
  var cheerio, sContent, spider, superagent;

  superagent = require('superagent');

  cheerio = require('cheerio');

  sContent = require('./sContent');

  spider = function(page) {
    return this.page = page;
  };

  spider.prototype = {
    getData: function(response) {
      return superagent.get(this.page).end(function(err, res) {
        var $, topics, users;
        if (err) {
          return console.error(err);
        } else {
          console.log('the page is:' + this.page);
          users = [];
          topics = [];
          $ = cheerio.load(res.text);
          $('#topic_list div.cell').each(function(idx, data) {
            var $topic, $user;
            $user = $(this).find('a').first();
            users.push({
              name: $user.find('img').attr('title').trim(),
              img: $user.find('img').attr('src').trim(),
              href: 'https://cnodejs.org' + $user.attr('href').trim()
            });
            $topic = $(this).find('div.topic_title_wrapper');
            return topics.push({
              istop: $topic.find('span').first().text().trim(),
              title: $topic.find('a.topic_title').attr('title').trim(),
              href: 'https://cnodejs.org' + $topic.find('a.topic_title').attr('href').trim(),
              replies: $(this).find('span.count_of_replies').text().trim(),
              visits: $(this).find('span.count_of_visits').text().trim()
            });
          });
          return console.log(users, topics);
        }
      });
    }
  };

  module.exports = spider;

}).call(this);
