// Generated by CoffeeScript 1.10.0
(function() {
  var cheerio, spider, superagent;

  superagent = require('superagent');

  cheerio = require('cheerio');

  spider = function(page) {
    return this.page = page;
  };

  spider.prototype = {
    getData: function(response) {
      return superagent.get(this.page).end(function(err, res) {
        var $;
        if (err) {
          return console.error(err);
        } else {
          $ = cheerio.load(res.text);
          $('#topic_list div.cell+a').each(function() {
            console.log($(this).attr('href'));
            return console.log('================================');
          });
          return response.send({
            tilte: 'express',
            data: ""
          });
        }
      });
    }
  };

  module.exports = spider;

}).call(this);
